// Thay thế đoạn app.get('/raw-hub', ...) trong server.js cũ:
app.get('/raw-hub', async (req, res) => {
    try {
        const { data } = await getFileFromGithub();
        res.setHeader('Content-Type', 'text/plain; charset=utf-8');
        
        // Khởi tạo cấu trúc trả về dạng Table Lua
        let luaOutput = `-- Generated by Anscript Hub v2\n`;
        luaOutput += `local HubData = {\n`;
        
        // Thông tin chung & Màu sắc UI
        luaOutput += `  Info = {\n`;
        luaOutput += `    Name = "${data.hubInfo.name || 'Anscript Hub'}",\n`;
        luaOutput += `    Version = "${data.hubInfo.version || '1.0'}",\n`;
        luaOutput += `    Creator = "${data.hubInfo.creator || 'An'}",\n`;
        luaOutput += `    ImageId = "${data.hubInfo.imageId || ''}",\n`;
        luaOutput += `    ThemeColor = "${data.hubInfo.themeColor || '#00adb5'}"\n`;
        luaOutput += `  },\n`;

        // Dữ liệu cấu trúc Tab Home riêng biệt
        const home = data.homePage || { introText: '', elements: [] };
        luaOutput += `  Home = {\n`;
        luaOutput += `    Intro = [[${home.introText || 'Chào mừng đến với Anscript Hub'}]],\n`;
        luaOutput += `    Elements = {\n`;
        if (home.elements) {
            home.elements.forEach(el => {
                luaOutput += `      { Type = "${el.type}", Text = "${el.text}", Value = "${el.value || ''}" },\n`;
            });
        }
        luaOutput += `    }\n`;
        luaOutput += `  },\n`;

        // Dữ liệu các Tab tính năng và Script
        luaOutput += `  Tabs = {}\n`;
        luaOutput += `}\n\n`;

        // Đổ dữ liệu các Tab (Giữ nguyên logic cũ của ông)
        if (data.tabs) {
            data.tabs.forEach(tab => {
                luaOutput += `local tab_${tab.id} = { Name = "${tab.name}", Sections = {} }\n`;
                if(tab.sections) {
                    tab.sections.forEach(sec => {
                        luaOutput += `local sec_${sec.id} = { Name = "${sec.name}", Scripts = {} }\n`;
                        if(sec.scripts) {
                            sec.scripts.forEach(scr => {
                                luaOutput += `table.insert(sec_${sec.id}.Scripts, { Name = "${scr.name}", Desc = "${scr.desc}", Content = function()\n${scr.content}\nend })\n`;
                            });
                        }
                        luaOutput += `table.insert(tab_${tab.id}.Sections, sec_${sec.id})\n`;
                    });
                }
                if(tab.scripts) {
                    luaOutput += `tab_${tab.id}.StandaloneScripts = {}\n`;
                    tab.scripts.forEach(scr => {
                        luaOutput += `table.insert(tab_${tab.id}.StandaloneScripts, { Name = "${scr.name}", Desc = "${scr.desc}", Content = function()\n${scr.content}\nend })\n`;
                    });
                }
                luaOutput += `table.insert(HubData.Tabs, tab_${tab.id})\n\n`;
            });
        }
        
        luaOutput += `return HubData`;
        res.send(luaOutput);
    } catch (error) {
        res.status(500).send(`-- Error: ${error.message}`);
    }
});
