const express = require('express');
const axios = require('axios');
const path = require('path');
const app = express();

app.use(express.json());
app.use(express.static(path.join(__dirname)));

// Lấy cấu hình từ biến môi trường của Render
const GITHUB_USER = process.env.N_ANS;
const GITHUB_REPO = process.env.R_ANS;
const GITHUB_TOKEN = process.env.T_ANS;
const FILE_PATH = 'data.json'; // File chứa dữ liệu script lưu trên GitHub

const githubApi = axios.create({
    baseURL: `https://api.github.com/repos/${GITHUB_USER}/${GITHUB_REPO}/contents/`,
    headers: {
        Authorization: `token ${GITHUB_TOKEN}`,
        Accept: 'application/vnd.github.v3+json'
    }
});

// Helper: Lấy file từ GitHub
async function getFileFromGithub() {
    try {
        const response = await githubApi.get(FILE_PATH);
        const content = Buffer.from(response.data.content, 'base64').toString('utf-8');
        return { data: JSON.parse(content), sha: response.data.sha };
    } catch (error) {
        // Nếu file chưa tồn tại, trả về cấu trúc mặc định
        if (error.response && error.response.status === 404) {
            return { data: { hubInfo: {}, tabs: [] }, sha: null };
        }
        throw error;
    }
}

// Helper: Lưu file lên GitHub
async function saveFileToGithub(data, sha) {
    const contentBase64 = Buffer.from(JSON.stringify(data, null, 2)).toString('base64');
    const body = {
        message: 'Cập nhật dữ liệu từ Anscript Hub Panel',
        content: contentBase64
    };
    if (sha) body.sha = sha;
    await githubApi.put(FILE_PATH, body);
}

// API: Lấy toàn bộ dữ liệu
app.get('/api/data', async (req, res) => {
    try {
        const { data } = await getFileFromGithub();
        res.json(data);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// API: Cập nhật toàn bộ dữ liệu
app.post('/api/data', async (req, res) => {
    try {
        const { data, sha } = await getFileFromGithub();
        await saveFileToGithub(req.body, sha);
        res.json({ success: true });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// API: Endpoint trả về raw script phục vụ cho Roblox thực thi (game:HttpGet)
app.get('/raw-hub', async (req, res) => {
    try {
        const { data } = await getFileFromGithub();
        res.setHeader('Content-Type', 'text/plain; charset=utf-8');
        
        // Tạo chuỗi Lua kết quả trả về cho Roblox script
        let luaOutput = `-- Generated by Anscript Hub\n`;
        luaOutput += `-- Hub: ${data.hubInfo.name || "Unnamed"} | Ver: ${data.hubInfo.version || "1.0"} | By: ${data.hubInfo.creator || "Unknown"}\n`;
        luaOutput += `-- Image ID: ${data.hubInfo.imageId || ""}\n\n`;
        
        luaOutput += `local HubData = {\n`;
        luaOutput += `  Info = { Name = "${data.hubInfo.name || ""}", Version = "${data.hubInfo.version || ""}", Creator = "${data.hubInfo.creator || ""}", ImageId = "${data.hubInfo.imageId || ""}" },\n`;
        luaOutput += `  Tabs = {}\n`;
        luaOutput += `}\n\n`;

        data.tabs.forEach(tab => {
            luaOutput += `local tab_${tab.id} = { Name = "${tab.name}", Sections = {} }\n`;
            tab.sections.forEach(sec => {
                luaOutput += `local sec_${sec.id} = { Name = "${sec.name}", Scripts = {} }\n`;
                sec.scripts.forEach(scr => {
                    luaOutput += `table.insert(sec_${sec.id}.Scripts, { Name = "${scr.name}", Desc = "${scr.desc}", Content = function()\n${scr.content}\nend })\n`;
                });
                luaOutput += `table.insert(tab_${tab.id}.Sections, sec_${sec.id})\n`;
            });
            // Script ở ngoài section nhưng thuộc tab
            if(tab.scripts) {
                luaOutput += `tab_${tab.id}.StandaloneScripts = {}\n`;
                tab.scripts.forEach(scr => {
                    luaOutput += `table.insert(tab_${tab.id}.StandaloneScripts, { Name = "${scr.name}", Desc = "${scr.desc}", Content = function()\n${scr.content}\nend })\n`;
                });
            }
            luaOutput += `table.insert(HubData.Tabs, tab_${tab.id})\n\n`;
        });
        
        luaOutput += `return HubData`;
        res.send(luaOutput);
    } catch (error) {
        res.status(500).send(`-- Error loading hub data: ${error.message}`);
    }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
